name: 'Secrets Pipeline'

on:
  workflow_run:
    workflows: ['Normal Pipeline']
    branches: [master]
    types:
      - completed
  push:
    paths:
    - '**/secrets.yml'

jobs:
  restart_ecs:
    name: 'Le secrets Pipeline'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dirs: [development, staging, production]
    - name: Will run only if a secrets file changed
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      run: |
        cd ${{ matrix.dirs }}
        cat secrets.yml
